import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/layout";
import { Providers } from "@/components";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <SessionProvider>
          <Providers>
            <Layout>{children}</Layout>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
